name: Render Docs

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  render_docs:
    name: 'Render Docs'
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install Asciidoctor
        run: |
          sudo chown -R $USER /var/lib/gems/
          sudo chown -R $USER /usr/local/bin
          gem install asciidoctor
        shell: bash

      - name: Render Docs
        run: asciidoctor ./*.asc

      - name: Publish Rendered Site As Artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs.ankidroid.org
          path: ./
